### ISSUE TITLE
UseSkipList doesn't work

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#1000]
* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.1.1 (released)

`*FvwmPager: UseSkipList`

Does not hide modules and windows that are using the WindowListSkip style.

**Comment by ThomasAdam** [comment]
@somiaj -- I think this is due to commit fbfedabcb85bd0b6e6978c6d7e035afcc8dd7d19 -- any chance that logic could be reintroduced?

@rasatpc -- how are you building fvwm3?  1.1.1 is not a release of fvwm3, so I'm guessing you must be building from a .zip archive or something?  Not sure why you'd do that...

**Comment by somiaj** [comment]
I'll take a look at it, I'll see what I missed and figure out how to correctly filter out the windows on the skip list.

**Comment by rasatpc** [comment]
> how are you building fvwm3?

I am not using a fork or git clone but downloading from Fvwm3 GitHub website. Green button "`<> Code`" Download ZIP.

**Comment by somiaj** [comment]
@rasatpc just git clone, and build from the git source, that zip method isn't really a nice way to go about things. This will also help you learn git more.

**Comment by somiaj** [comment]
@rasatpc, see if #1001 fixes the issue for you.

**Comment by rasatpc** [comment]
> that zip method isn't really a nice way to go about things.

I will not change the method. I am doing the test as per how common Fvwm users will do. This is how I find bugs that go unnoticed by the developers.

> see if #1001 fixes the issue for you.

Thanks, it works fine.
