### ISSUE TITLE
Latest fvwm seems to do away with negative numbered desks.

### ISSUE THREAD

**Issue by ileGITimo** [fvwmorg/fvwm3#1045]
Mentioned in issue #1044, opening as separate issue.

Latest code (as of sometime last week)  does away with negative numbered desks.

As someone that has mostly used pagers with desks -1 to 1 or -2 to 2, ever since there were desks, and have lots of StartsOnPage with negative desks, I feel lost.

**Comment by ThomasAdam** [comment]
I can appreciate that.  However, the EWMH specification does say there shouldn't be any negative desk numbers.

It is technically a breaking change, but I would argue that there's very few users of *negative* desks.

**Comment by somiaj** [comment]
Note, I broke negative desks in the pager due to some other changes (it was not intentional), as I didn't realize negative desks could be used (since I haven't seen it before and as mentioned the EWMH spec only supports non-negative desks).

In short fvwm3 still supports negative desks, it is only FvwmPager that no longer shows them. It wasn't intentional to cause this breakage, but it isn't worth fixing (fix is non trivial now), and it is probably best you stop using negative desks (since other applications that follow the EWMH spec may also get confused if you put windows on negative desks).

**Comment by ileGITimo** [comment]
I've been using fvwm for over 30 years.  As soon as there were desks I always had multiple desks, centered around 0.  My desktop is Nx1, usually paging from -1 to +1, sometimes I need to switch back and forth to/from -2 to +2 by restarting the pager in some of my monitors.   Getting rid of the negative windows is both, simply done by editing a few config files, and incredible hard to retrain my 30 year old brain muscle memory.

**Comment by ileGITimo** [comment]
> In short fvwm3 still supports negative desks, 

This is not the case.  Changes that added "Desk N" to the Move command, in both fvwm/move_resize.c and fvwm/update.c,  do not handle negative desks.
