### ISSUE TITLE
Vector button is drawn incorrectly

### ISSUE THREAD

**Issue by rc-pl** [fvwmorg/fvwm3#1065]
Default config for fvwm3 has this code for drawing "x" (close button) 

AddButtonStyle 2 Active Vector 4 35x35@3 65x65@3 65x35@4 35x65@3

it draws "x" with top right arm shorter

![image](https://github.com/user-attachments/assets/f8b131a9-2cba-4e70-8cde-7757b4d6f938)

changing this code to 

AddButtonStyle 2 Active Vector 4 35x35@3 65x65@3 35x65@4 65x35@3

somehow fixes it

![image](https://github.com/user-attachments/assets/01b61cda-dc8a-4f46-a746-aeb39810816b)

**Comment by somiaj** [comment]
This is a rounding issue, since vectors always use coordinates between 0 and 100, and then scale to size of the vector button. It might just be that in the logic of the vector drawing, the rounding issue isn't seen if you draw the line the other direction.

I have noticed this before, and have also noticed that it depends on the size of the title bar, on some of my machines it is one pixel short and on others it is not.

I will update the default config as you suggest, though it might just be that for some users that didn't get the rounding error before will now get it.

**Comment by somiaj** [comment]
default-config updated in #1066 to the suggestion here.
