### ISSUE TITLE
Two issues with the WindowList

### ISSUE THREAD

**Issue by okraits** [fvwmorg/fvwm3#151]
`Silent Key Tab A M WindowList (CurrentDesk,!Iconic) Root c c CurrentAtEnd,NoCurrentDeskTitle`

The menu title with the desk name/num should not appear with `NoCurrentDeskTitle` set. But if there aren't any windows on that desktop, it appears (with no menu items except the title).

`Silent Key a A 4 WindowList Root c c TitleForAllDesks,NoCurrentDeskTitle,NoGeometryWithInfo`

If `NoGeometryWithInfo` is set, then the menu items don't include the window titles.

Using fvwm3 8ba1ac7009f45d16a08ec1eedb9cdd61615fb789

**Comment by somiaj** [comment]
@okraits, I have looked at this a bit and think I have figured out the second issue.

> `Silent Key Tab A M WindowList (CurrentDesk,!Iconic) Root c c CurrentAtEnd,NoCurrentDeskTitle`
> 
> The menu title with the desk name/num should not appear with `NoCurrentDeskTitle` set. But if there aren't any windows on that desktop, it appears (with no menu items except the title).
>
What do you think should happen if there is nothing to show? Should a Menu open just saying "Empty"? I think this is just a side effect of that it is probably better for a Menu to open vs do nothing in the case there is nothing to show.

> `Silent Key a A 4 WindowList Root c c TitleForAllDesks,NoCurrentDeskTitle,NoGeometryWithInfo`
> 
> If `NoGeometryWithInfo` is set, then the menu items don't include the window titles.
> 
> Using fvwm3 [8ba1ac7](https://github.com/fvwmorg/fvwm3/commit/8ba1ac7009f45d16a08ec1eedb9cdd61615fb789)

This second issue could be due to the default-confg or the `Menu * ItemFormat` option. In the default config the ItemFormat only defines a single column, but in this case the menu created uses two columns, one for the number and two for the window name. If the second column isn't defined in `ItemFormat`, then it won't show despite what options you send. I was able to fix this issue by using the following ItemFormat (or just grab the default one from the manual page and edit).

```
MenuStyle * ItemFormat "%|%3.1i%5.3l%3l%3r%5.3>%|"
```
