### ISSUE TITLE
Safe sprintf call

### ISSUE THREAD

**Issue by klebertarcisio** [fvwmorg/fvwm3#164]
Hi everyone,

I would like to know what do you think about these sprintf calls:

https://github.com/fvwmorg/fvwm3/blob/48dd50909b97170d517aa02c735cc86881564cb6/modules/FvwmIdent/FvwmIdent.c#L1332-L1335

In this case, x and y are integer variables, but max_aspect is a char of just 11 bytes.
See this toy example:
**sprintf (mymin_aspect, "% d % d", 111111, 111111);**
In this case, we have an overflow. Should the **mymin_aspect** variable be **24** bytes?

https://github.com/fvwmorg/fvwm3/blob/48dd50909b97170d517aa02c735cc86881564cb6/libs/Colorset.c#L111-L120

In this case, **csetbuf** is a char of just **256** bytes, but the operation requires **270** bytes.

https://github.com/fvwmorg/fvwm3/blob/48dd50909b97170d517aa02c735cc86881564cb6/fvwm/icccm2.c#L56-L56

In this case, **wm_sx** is a char of just **20** bytes, but the operation requires **25** bytes.

Regards

**Comment by ThomasAdam** [comment]
Hi @klebertarcisio,

Yes, the compiler is starting to spit these warnings out now, as is the static analysis tool we're using.  See:

https://github.com/fvwmorg/fvwm3/issues/107

I'm all for fixing these, however, what I'd rather see are things like this changed as a result of bug-fixes in that area of the code, rather than necessarily going through all of these things piecemeal.

A lot of what you're identifying is code which has been there for many years, and although compilers are now getting smarter, the code itself isn't causing any problems.  We will fix these, but I'd much rather see some of the issues blocking a 1.0 release looked at first:  https://github.com/fvwmorg/fvwm3/projects/1?card_filter_query=milestone%3A1.0

**Comment by ThomasAdam** [comment]
Hi @klebertarcisio,

Now that things have started to settle -- can you revisit this?

**Comment by klebertarcisio** [comment]
Hi @ThomasAdam, yes, I can do it!

**Comment by ThomasAdam** [comment]
Hi @klebertarcisio 

I hope you're well.  Just checking to see if you think you'll be able to look at this issue soon?  If not, I'll close this and move this in to the TODO list.

No pressure -- just trying to do some project maintenance.

**Comment by klebertarcisio** [comment]
Hi @ThomasAdam, sorry for my delay. I create a pull request about this issue. [Here](https://github.com/fvwmorg/fvwm3/pull/306)
