### ISSUE TITLE
New versioning scheme of FVWM3 RC0 break Version test condition.

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm3#195]
Hi,

Things like:

Test (Version >= 3.0.0) SetEnv FVWM3_LOGFILE ~/.NsCDE/tmp/fvwm3.log
Test (Version >= 3.0.0) InfoStoreAdd xlogcmd "tail -300f ~/.NsCDE/tmp/fvwm3.log"

Worked during development and playing/testing with fvwm3, but now with RC0 this returns 1.0.0, which is way to small for this, and even triggers a trigger which checks if it is >= 2.6.7.

It is not clear if this 3 in "fvwm3" is major release number or part of the name, but because 95% or more of the configuration parameters for fvwm2 and fvwm3 are the same, there should really be this or some other mechanism how to distinguish it is 2.6.X or 3.X.X or bigger. For adaptive configurations, specially for those who use FVWM as framework, this may be important. :-)

**Comment by ThomasAdam** [comment]
Hmm.  I daresay an RC-X might break this.  Still not sure about 3.0.0 -- that is misleading, since it's not the 3rd release of fvwm3, it's the first release at 1.0.0

**Comment by NsCDE** [comment]
You should definitely make some choice and consistent system here.

P. S.
I have sent mail about FvwmMFL on fvwm@fvwm.org, I'm subscribed (at least I think I am) I don't know why my messages get stalled and do not reach the list.

**Comment by ThomasAdam** [comment]
Probably HTML email.  Send it to me directly:  thomas@fvwm.org

**Comment by ThomasAdam** [comment]
Right now, the convenience of using the same configuration file between fvwm2 and fvwm3 is just that -- convenience.  I know I keep saying the syntax hasn't changed, and that you can (at the moment) use the same config file on both -- that's still true.

But at some point soon, they will diverge, and at that moment, that's when I won't be able to support having one config file for both.  Right now, I'm thinking about fvwm3's future.

Rather than using a version check (which I *will* be removing in Fvwm3 soon enough as it's fundamentally broken), we could instead have an environment variable or something else in Fvwm3 which can be check for, a la `EnvIsSet`.  This would be equivalent to the version check; that is to say:  either fvwm3 or fvwm2.

**Comment by ThomasAdam** [comment]
Please see https://github.com/fvwmorg/fvwm3/commit/9b4a2405b29486393f6fbc938bd266d1c8162508 as a stop-gap for now.
