### ISSUE TITLE
FvwmPager: moving windows inside FvwmPager is inconsistent

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#198]
When `FvwmPager` became `per-monitor` aware, this worked for scrolling around pages.  But this no longer works very well when moving windows within `FvwmPager` to new desks/pages.

@somiaj has the following logic to fix this:

```
# Definitions
#   nx = Number of Pages in the Horizontal Direction
#   ny = Number of Pages in the Vertical Direction
#
#   px = x-coordinate of window in pager.
#   py = y-coordinate of window in pager.
#
#   PagerWidth = Width of Pager Window
#   PagerHeight = Height of Pager Window
#   (This is for a single desktop)
#
#   DisplayWidth = Width of display (single page)
#   DisplayHeight = Height of display (single page)
#
#   mx = monintor's x-coordinate
#   my = monintor's y-coordinate
#
#   Vx = x-coordinate of current viewport
#   Vy = y-coordinate of current viewport

# Get size of a single page
PageWidth = PagerWidth / nx;
PageHeight = PagerHeight / ny;

# Get current page
Pagex = px / PageWidth;
Pagey = py / PageHeight;

# Get coordinates relative to current page and
# scale coordinates to full display.
cx = (px % PageWidth) * DisplayWidth / PageWidth;
cy = (py % PageHeight) * DisplayHeight / PageHeight;

# Compute display coordinates
x = Pagex * DisplayWidth + cx + mx
y = Pagey * DisplayHeight + cy + my

# Adjust Coordinates to Current Display
t->x = x - Vx
t->y = y - Vy
```

This is probably all via `modules/FvwmPager/x_pager.c:MoveWindow()`

**Comment by phintsan** [comment]
(I don't know if this is the same issue than this one, but for me this is "inconsistent" so I'm adding this report here.)

Here is another sequence in FvwmPager which causes erratic behaviour:

1. Start fvwm3 with the default configuration.
2. Open FvwmConsole.
3. Issue "Module FvwmPager 0 1" command.
4. Drag FvwmConsole window to Desk 1 in the pager. Do this so that the window overlaps the desk boundary and release mouse button on top of Desk 1.

Expected behaviour: FvwmConsole is on Desk 1, partially outsize the virtual screen.
Observed behaviour: FvwmConsole is on Desk 0, partially visible on FvwmPager but invisible on the screen.

I have seen similar mess-ups after other moves between desks, but this is probably the easiest way to reproduce the problem.

This is a regression caused by a22beb13. The problem is in macro UPDATE_FVWM_SCREEN, presumerably in CMD_Move function. In screen.h:490 there is an assignment 

  (fw)->Desk = mnew->virtual_scr.CurrentDesk; 

This overrides the correct fw->desk by wrong mnew... desk coming from FindScreenOfXY call at line 483. Removing that assignment fixes the problem, but I don't know if it causes any regressions elsewhere since I'm not really familiar with the code.

**Comment by ThomasAdam** [comment]
Hi @phintsan 

Thanks for your observations.  There's multiple breakages in `FvwmPager` with the changes made to support `DesktopConfiguration per-monitor`.  This has unfortunately also impacted the default behaviour of `DesktopConfiguration global` as well.  As the notes above hint at, I just need to sit down and fix it.  ;)

It's certainly not enough to comment out the `(fw)->Desk` assignment in `UPDATE_FVWM_SCREEN` as this would break everything.   Better for now, would be to stop FvwmPager inferring the desk the window is on, and let Fvwm update that via the `FvwmPager` is sending fvwm directly (`Move`, etc.)

Perhaps `ta/fvwmpager-dont-update-desk` improves this a little?  Either way, although it might help keep the window on screen, there's no magic bullet here -- I need to rewrite this entire logic to truly fix this.

**Comment by phintsan** [comment]
@ThomasAdam 

Thanks for your prompt reply. At a glance `ta/fvwmpager-dont-update-desk` seems to fix the problem: after moving the window in the pager it stays on Desk 1 (in the pager), but switching to that desk does not bring the window visible on the screen. The window reappears on the screen after returning to Desk 0, but it stays on Desk 1 in the pager.

I'm afraid there is not much more for me to do here until you've sorted it out, after which I can help with testing.
Thanks for your efforts.
