### ISSUE TITLE
Proposal: FvwmEvent new events in FVWM3

### ISSUE THREAD

**Issue by NsCDE** [fvwmorg/fvwm3#26]
As FvwmEvent handles new_page and new_desk window manager event, it will be nice to make RandR screen events acessible through it.

According to debug output, FVWM3 sees when monitor is added or removed, enabled or disabled, or when pointer changes active screen.

Proposal for exposing events is:

add_monitor
remove_monitor
enable_monitor
disable_monitor
change_screen

That way, user can configure custom actions and functions for this situations if wanted/needed.

**Comment by ThomasAdam** [comment]
Hi,

So please see the `ta/gh-26` branch which implements the following hooks in `FvwmEvent`:

* monitor_enabled -- when a monitor is "plugged" in, and active;
* monitor_disabled -- when a monitor is "unplugged" and deactivated;
* monitor_changed -- when an enabled monitor changes resolution/rotation

Due to how RandR works, the finer-grained distinction between enable/add and disable/remove aren't reliable at all.  But hopefully the above three should help cover most basis that people are interested in.

I've also added an example to `man FvwmEvent`.

**Comment by ThomasAdam** [comment]
Hi,

This has been working well enough for me, and hence I'll merge the pull-request associated with this issue, to master.

Feel free to open a new issue if there's problems.

Thomas
