### ISSUE TITLE
Feature Request: Add a customizable notification daemon to fvwm

### ISSUE THREAD

**Issue by sarishinohara** [fvwmorg/fvwm3#354]
Having a builtin notification daemon in a window manager sounds like a pretty appealing  idea. AwesomeWM already has it (Naughty), and I've seen a lot of people who liked that feature.

**Comment by danespen** [comment]
hisao <notifications@github.com> writes:

> Having a builtin notification daemon in a window manager sounds like a
> pretty appealing idea. AwesomeWM already has it (Naughty), and I've
> seen a lot of people who liked that feature.

It would be dumb to have it built in.  There is no necessary
relationship between a notification daemon and a window manager.
Just install any notification
daemon you want to use.  There's probably one already in your distro.

A while back I installed 'dunst' on my system because it's the most
configurable notification daemon I could find.

-- 
Dan Espen

**Comment by sarishinohara** [comment]
Hi @danespen 
Why dumb? I like the idea of my window manager having a customizable notification daemon without the need to install additional software. What if dunst becomes unmaintained at some point? Too much dependency on external will limit the potential of a WM. AwesomeWM has this feature and i've seen a lot of users who were more than happy with it. no harm in making FVWM more featurefull.
Btw I already use dunst myself and I like it, it was just an idea that I thought the devs might consider and I'm not gonna like that I'm curious what they could come up with.

**Comment by danespen** [comment]
hisao <notifications@github.com> writes:

> Hi @danespen

> Why dumb? I like the idea of my window manager having a customizable
> notification daemon without the need to install additional
> software. What if dunst becomes unmaintained at some point? Too much
> dependency on external will limit the potential of a WM.  AwesomeWM
> has this feature and i've seen a lot of users who were more than happy
> with it. no harm in making FVWM more featurefull.  Btw I already use
> dunst myself and I like it, it was just an idea that I thought the
> devs might consider and I'm not gonna like that I'm curious what they
> could come up with.

Sorry, maybe dumb isn't the right word.

I'm not doing development, so this is just an opinion.
Fvwm is a window manager and over the years it has striven to NOT
become a desktop environment.

Dunst wouldn't be any better than it is if it was made part of Fvwm.

-- 
Dan Espen

**Comment by NsCDE** [comment]
This is my view and opinion about this and similar why-my-wm-doesnt-make-coffee:

There will always be standalone components from which every window manager user can build lesser or larger part of the desktop environment. Like stalonetray, dunst, xsettingsd, xscreensaver etc. Lot of people really need and use this.

The good thing about this software is precisely that it is WM independent, and customizable to fit the user's needs. Window Manager itself, specially a powerful one like FVWM does not need to reinvent the wheel in a way that only FVWM can use it, adding most probably additional pressure on developer(s).

Unfortunately, many people does not understand that this attitude only limits software quality, flexibility and maintainability. Good interfaces and standards is what is needed, so components can integrate.

One philosopher noticed how trouble can emerge from not recognizing already fulfiled state: making ilusion and searching for some holly grail, and during this quest, losing what was already there. Like replacing dunst ... or otherwise dumping perfectly usable software and whole substems for the sake of change on it's own and solving the problem that didn't exist in the first place.

Just my 200 €. :-)

**Comment by sarishinohara** [comment]
Hi @NsCDE And thank you and @danespen for your input.
I didn't think _FVWM_ users would be so strongly against something like this, afaik the dev didn't mind it much when i first shared it with him.
Ofc I'm in no way intending to put any additional pressure or work on the dev, for now _FVWM_ is doing exactly what i want and need, I was just asked to document any ideas or features that I thought would make _FVWM_ better than it's peers. 
I used a lot of window managers before settling with _FVWM_, and i only picked the features I thought _FVWM_ was missing compared to them (which, again, a lot of users appreciated, so it's not just a random idea out of the back of my mind), even if they're not strictly as important to other _FVWM_ users. 
For now, I don't think I will change my mind about it, A notification daemon wouldn't make _FVWM_ suddenly all bloaty, and it doesn't need to be a heavy feature with unlimited customization options, just a light function that integrates better with the rest of _FVWM_ components, which can be disabled if the user prefers other external software.
This remains a **TODO** idea for now, I don't mind if it's rejected in the future and I appreciate all the input I can get to put things into perspective.

**Comment by lgsobalvarro** [comment]
I have talk about this with @ThomasAdam in the past. In fact I did requested this to him a couple of months ago. In the end I changed my mind. While having a built-in notification daemon could be convenient (just as well as a tray) it's important to mention that FVWM has always aim at being light and flexible, letting the user choose by itself what he wants.
The thing is, there is plenty of stand-alone notification daemons out there. You can easily use dunst, xfce4-notifyd, lxde-notificationd, notification-daemon, mate-notification-daemon... just to mention a few. There is not much point in creating just another notification daemon for FVWM just for convenience, specially when 90% of the development is being done by @ThomasAdam and there is plenty of more important things to focus on, than a notification-daemon.
This topic could be revisit in the future once more important targets have been archived.

**Comment by ThomasAdam** [comment]
Hi,

Thanks all for your comments.   I think there's something to be said about what a window manager should provide, and what can be used externally to it, and that's always been FVWM's philosophy.  Heck, even the well-known and used modules such as `FvwmButtons` and `FvwmIconMan` are modules because they're optional bits of functionality that users are free to use if they want to, rather than having it forced on them.

So I think that's the point here -- pretty much every notification daemon I've seen (and I happen to use `dunst`) uses DBus, and the `notify-bin` wrapper understands how to talk to most/all (?) notification-daemons.  So it wouldn't be hard at all to wrap that up in a module.  That's also another point worth mentioning:  WMs (FVWM in particular) are often designed to be extended if the precise functionality you want doesn't exist.  So writing a proof-of-concept module that uses `FvwmEvent` or `FvwmMFL` to then fire off requests to `notify-bin` isn't difficult at all.  That is, after all, the spirit of window management -- notifications are completely orthogonal to that.

So no, I don't think I'm necessarily in favour of adding this to FVWM directly.

**Comment by sarishinohara** [comment]
> So writing a proof-of-concept module that uses FvwmEvent or FvwmMFL to then fire off requests to notify-bin isn't difficult at all. That is, after all, the spirit of window management -- notifications are completely orthogonal to that.

That's exactly what i had in mind. I probably didn't articulate it well enough.

> So I think that's the point here -- pretty much every notification daemon I've seen (and I happen to use dunst) uses DBus, and the notify-bin wrapper understands how to talk to most/all (?) notification-daemons. So it wouldn't be hard at all to wrap that up in a module.

That's probably the way to go about it. 

> So no, I don't think I'm necessarily in favour of adding this to FVWM directly.
When you put it like that, neither am I.
What i wanted isn't to inject the function directly into FVWM itself but possibly create a _notification_ module that users are free to use or discard. of course this shouldn't be the main focus for now, just something that might be revisited later once the more important development tasks are cleared.

**Comment by ThomasAdam** [comment]
Even something such as:

```
echo "set focus_change" | nc -U $FVWMMFL_SOCKET | while read a; do notify-send "from $(echo "$a" | jq '.focus_change.window')"; done
```

Or you can do it directly from `FvwmEvent` -- it depends on your needs.
