### ISSUE TITLE
Pager do not show smalls windows in the correct place when snapped to the edge

### ISSUE THREAD

**Issue by lgsobalvarro** [fvwmorg/fvwm3#541]
## Upfront Information

Please provide the following information by running the command and providing
the output.

* Fvwm3 version (run: `fvwm3 --version`)

1.0.4 (1.0.3-23-g75ebba90)

* Linux distribution or BSD name/version
openSUSE Tumbleweed

* Platform (run: `uname -sp`)
Linux x86_64

## Actual Behaviour
Due the last changes made to Pager smalls windows are not snapped correctly to the edge/border.

## Steps to Reproduce
Spawn Pager (Buttons or any window) and set geometry to a small size (64x192-0+0 for instance).
This also affects iconified windows when they are near the edge of the screen

* Does the problem also happen with Fvwm2?
No

## Does Fvwm3 crash?
No

## Extra Information
![2021-06-17-163246_74x200_scrot](https://user-images.githubusercontent.com/1160397/122477844-01f3e980-cf8e-11eb-9643-36f52faf49dd.png)

![2021-06-17-163318_74x48_scrot](https://user-images.githubusercontent.com/1160397/122477851-04564380-cf8e-11eb-8571-be0c1f3faeb4.png)

![2021-06-17-163639_77x47_scrot](https://user-images.githubusercontent.com/1160397/122477873-0a4c2480-cf8e-11eb-9f08-d4b6809d3f6c.png)

**Comment by somiaj** [comment]
@lgsobalvarro Check out js/gh-541, it updates the logic when setting mini windows to the minimum size, which will help prevent windows from appearing on the wrong page, by snapping them to the page boundary. In addition this reduces the minimum size to 3 pixels by default, and adds a `WindowMinSize` option to configure the minimum size.

In general when a mini window is set to the minimum size, since its relative size is different than the other scaled aspects (pages, monitor positions, and other window positions), the window may appear miss aligned with other windows which will be most noticeable using a small pager. Beyond this snapping to page boundaries, I see no point to try to add logic to fix other possible issues. You can now reduce the `WindowMinSize` to 1 to get the old default size.
