### ISSUE TITLE
Testing notes for FVWM3-rc.X release candidate

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#65]
Hi all,

As determined by me (which is arbitrary), there's a few more things left to sort before a potential release candidate, but [not too much](https://github.com/fvwmorg/fvwm3/projects/1).

As of what's on `master` now, I'd like as much focus on the following to be tested, please.  Leave any comments below.

* DesktopConfiguration:
  * global:
    * Are icons placed correctly with different `IconBox` styles?
    * Are windows placed correctly with different X11 `geometry` strings?  (`80x24+32+32` for example)
    * Test styles:  `StartsOnScreen, SkipMapping, StartsOnDesk, StartsOnPage`
  * per-monitor:
     * Configure per-screen `IconBox` styles.  Are icons placed correctly?  Are they retained after a reboot?
     * Test styles:  `StartsOnScreen, SkipMapping, StartsOnDesk, StartsOnPage`

* What happens when you switch between `global` and `per-monitor` `DesktopConfiguration` dynamically in `FvwmConsole` while `FVWM3` is running?

* Restarting FVWM3:
  * Are windows retained across desks/pages/monitors correctly;
  * Are icons retained across desks/pages/monitors correctly?

Plus, anything else!

**Comment by lgsobalvarro** [comment]
> Are icons placed correctly with different IconBox styles?

Yes. It works well with my custom config. I have set some custom icons for some apps, and they works fine too with IconBox.
>Are windows placed correctly with different X11 geometry strings? (80x24+32+32 for example)

Yes. My FvwmButtons is set as 64x64-0+0. Is set correctly
> Test styles: StartsOnScreen, SkipMapping, StartsOnDesk, StartsOnPage

I tried out StartsOnPage. Works well.
> Configure per-screen IconBox styles. Are icons placed correctly? Are they retained after a reboot?

Yes. As far as I know. I'll keep testing this.
>Test styles: StartsOnScreen, SkipMapping, StartsOnDesk, StartsOnPage

I need to keep testing this too.
> Are windows retained across desks/pages/monitors correctly;

No. Windows where retained across monitors, but it worked weird across desks and pages. I'll keep testing and try to figure out why.
>Are icons retained across desks/pages/monitors correctly?

I'm not sure. It felt like it is a bit glitchy. I'll keep testing it too.

**Comment by afhp-2020** [comment]
> Are windows placed correctly with different X11 geometry strings?

If you mean, does fvwm respect the geometry specification from a command-line, e.g. `xterm -geometry +2000+300`, yes.

> SkipMapping

Quick test : in FvwmConsole `Style Transgui StartsOnPage 3, SkipMapping` then start the program : `SkipMapping` is ignored, the window opens on Desk 3 and we switch to it.

**Comment by afhp-2020** [comment]
Scratch my comment on SkipMapping.

`Style xcalc StartsOnPage 3, SkipMapping` in FvwmConsole followed by either `Exec xcalc` or starting xcalc from an xterm results in the expected behavior: xcalc opens on the requested desk and focus is *not* switched to it.

**Comment by MasterP-theGu** [comment]
Hi,
sorry for having been away for so long. Our corona-rules seem to change on a day-to-day basis and I have to test and review them so that too little time is left for other stuff....

I've kept ma install updated to the most recent master branch in the past weeks on my productive machine. There's hardly anything that I notice that goes awry or not according to plan. NB: I currently "just use" fvwm3.
However, the one thing that makes me write "hardly" is still the pager. Every now and then (I cannot yet provide an estimate as to in which context), it loses open windows and seems to move others to 0:0. The windows are, of course, still available, and as soon as I switch to them, they're back in the game on the pager.

I mostly use DestopConfiguration per-monitor, but the pager trouble appears in both options.

**Comment by ThomasAdam** [comment]
https://github.com/fvwmorg/fvwm3/issues/195

**Comment by ThomasAdam** [comment]
Closing, as we're passed this now.
