### ISSUE TITLE
Firefox and Zoom windows are considered raised, when they're not

### ISSUE THREAD

**Issue by ThomasAdam** [fvwmorg/fvwm3#704]
Per @somiaj  on IRC:

```
         somiaj │ thomas_adam: do you know why some windows (firefox and zoom) will get classifed as 'Raised' even if a window is covering them?
    thomas_adam │ somiaj: No?  But I have firefox installed here, I can check...
         somiaj │ My simple test is 'Pick (Raised) Iconfiy' and both firefox and zoom will iconfiy even if covered by a window, but other windows won't
    thomas_adam │ Yeah, I see it here.
    thomas_adam │ That's odd.
         somiaj │ Yea, I noticed this with the default-config an trying to use FvwmIconMan to raise the window if it wasn't visible, and always had to click it twice on firefox due tot his
    thomas_adam │  Even putting FF in Layer 0 1 doesn't make any difference, fvwm thinks it's still raised.
```

Indeed, putting an xterm window over firefox and using:

```
Pick (Raised) Echo $[w.id] is raised
```

Shows FF to be raised, when it's covered by a window.  Issuing the same command on the `XTerm` window correctly identifies that window as raised.

**Comment by ThomasAdam** [comment]
This also happens with fvwm2 -- I wonder if the problem is with X11 somewhere?

**Comment by somiaj** [comment]
Adding the IRC info here. Firefox (and seems other apps) are not handling `VisibilityNotify` events correctly. This has been explicitly disabled in firefox, and other gtk3 apps may not support it, since gtk3 says this is not a reliable method to determine visibility with compositors.

+ Firefox Bug: <https://bugzilla.mozilla.org/show_bug.cgi?id=1654687>
+ Firefox commit which disabled `VisibilityNotify` events: <https://hg.mozilla.org/integration/autoland/rev/d84f3a60b553>
+ GtK3 event: <https://docs.gtk.org/gtk3/signal.Widget.visibility-notify-event.html> "Modern composited windowing systems with pervasive transparency make it impossible to track the visibility of a window reliably, so this signal can not be guaranteed to provide useful information." -- so could be over time less and less gtk3 apps use this event like firefox has done.

Should this just be closed as won't fix?
