### ISSUE TITLE
Missing transparency command

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#867]
## Upfront Information

For transparency to work at startup, add new command lines in default Fvwm config, in the InitBackground and SetBG functions. This activates RootTransparent and also to run any compositor for X11 (Picom, Compton, etc.)

Test (x fvwm-root) + I Exec exec fvwm-root -r ~/.fvwm/.BGdefault
Test (x fvwm3-root) + I Exec exec fvwm-root -r ~/.fvwm/.BGdefault

* Fvwm3 version (run: `fvwm3 --version`)
fvwm3 1.0.7 (1.0.6a-17-g01908e29)

* Linux distribution or BSD name/version
MX Linux

**Comment by rasatpc** [comment]
This modification works well on default config. At startup, activates RootTransparent. Also, immediately when changing the wallpaper.
Add these two lines after InitBackground function on line number 91

Test (x fvwm-root) Exec exec fvwm-root -r ~/.fvwm/.BGdefault
Test (x fvwm3-root) Exec exec fvwm-root -r ~/.fvwm/.BGdefault

These two lines attach to the SetBG function (at the end) on line number 134

+ I Test (x fvwm-root) Exec exec fvwm-root -r ~/.fvwm/.BGdefault
+ I Test (x fvwm3-root) Exec exec fvwm-root -r ~/.fvwm/.BGdefault

**Comment by ThomasAdam** [comment]
Hi @rasatpc 

I'm sure it does work well enough -- but there's already an open bug where transparency breaks using Steam -- because of how transparency works with backgrounds.

Given that, I'm not in favour of making this change.  Additionally, the point of the default config has already been reached, which is to allow the user to customise this at their leisure.
