### ISSUE TITLE
Desktop becomes unresponsive until <esc> is clicked when clicking right mouse button while holding left button on firefox tabs 

### ISSUE THREAD

**Issue by jonakselm** [fvwmorg/fvwm3#952]
## Upfront Information

* Linux distribution or BSD name/version
-- Arch Linux
-- Void Linux
-- Presumably all other linux distributions

* Platform (run: `uname -sp`)
Linux unknown (this is the actual output)

## What did I do

I missclicked and ended up clicking the right mouse button (MB2 I think) while holding down the left mouse button (MB1)

## Expected Behaviour

Nothing special happens and everything works fine.

## Actual Behaviour

Desktop becomes unresponsive while sound and terminals continues to work. Everything except for window input works (mouse events, focus, etc.). Mouse pointer can be moved but doesn't register focus anymore. Everything works again after pressing <esc>

## Steps to Reproduce

How can the problem be reproduced?  For this, the following is helpful:

* Use any config
* Open firefox
* Press down left mouse button
* Without lifting the left mouse button, press down the right mouse button
**Mouse icon should now be a grabbing hand and doesn't register mouse events anymore, making the desktop unresponsive**

* Does the problem also happen with Fvwm2?
 **Yes**

## Does Fvwm3 crash?

No

## Extra Information
Log contains nothing special, but I will provide if asked

**Comment by somiaj** [comment]
I don't think this is an issue with fvwm, I think firefox is grabbing the xserver, and fvwm has to wait until firefox is done with it. You will notice similar behavior if you grab a tab (hold left click and move the mouse) to move the tab. This too grabs the xserver and fvwm just has to wait until firefox is done. You can also see that firefox makes the escape key abort the action and release the xserver, just move a tab out of the way then hit escape.

I too see this behavior, and I see the same mini icon appear when moving the tab around when clicking both mouse buttons, but I am not able to move the tab icon. I think this is due to an issue in firefox itself triggering the option to move the tab, but not actually letting you. Note I haven't tested this on other wms).

**Comment by jonakselm** [comment]
This works without a problem in openbox. The moment either of the buttons are released, the grabbing hand returns to the default pointer

**Comment by ThomasAdam** [comment]
Not a fvwm issue.
