### ISSUE TITLE
FvwmPager Desk 0 shadow and unstable

### ISSUE THREAD

**Issue by rasatpc** [fvwmorg/fvwm3#960]
## Upfront Information

fvwm3 1.1.0 main branch

## Actual Behaviour
This image shows the default config with RightPanel. Desk 0 change to 1, 2 or 3) leaving a shadow. And Desk 0 page movement.
Screenshot:
https://rasatpc.net/screenshot/fvwm3/v110-main.png

1. Xterm and FvwmConsole on Desk 0 mini-window.
2. Desk 1 loaded with Xterm, shows a shadow of Desk 0 apps.
3. After Desk1, back to Desk 0, there has been a slight page movement towards right side.

Occasionally mini-window doesn't appear after a logout.
This could be a problem with the default config not being adjusted with the new changes.

**Comment by somiaj** [comment]
Your bug reports are a bit vague, and it took me a while to see what you were talking about. I think part of it comes form not fully understanding how things, in this case FvwmPager, work.

First, FvwmPager is not leaving 'shadows', note that the highlight of the desk changes, so what is happening is it appears that FvwmPager is only showing `Desk 0`, so when you change to `Desk 1`, you just don't see the desk you are currently on, but you do see `Desk 0` which is what the pager is showing, so no bug there. This is the difference between launching `FvwmPager` vs `FvwmPager *` (the `*` tells `FvwmPager` to track the current desk). The default-config correctly uses `FvwmPager *`.

As for the offset, that seems like you have used `Scroll` to only move partially across the pages. Note that since I know from a previous post you right click the pager, if you right click the pager you `Scroll` and the view port will be based off of where you click the mouse. In this case that is working as expected, as you are not viewing only page 0, 0, instead you have scrolled a bit to the right so your view port is overlapping part of page 1, 1, hence the offset. Fvwm provides the ability to move the view port so you can overlap multiple pages.

So far I cannot reproduce anything you have described, the only thing I've noticed in my tests is that sometimes FvwmPager would not run on startup (unsure why), but in the cases it does run, it appears to be functioning correctly.

**Comment by rasatpc** [comment]
@somiaj and @ThomasAdam  you wrote: Desk 0, so when you change to Desk 1, you just don't see the desk you are currently on, but you do see Desk 0 which is what the pager is showing, so no bug there.

In my test with default config, v 1.1.0 FvwmPager, I find it unstable. On first login everything is often fine. Then logout and login a few times. Restart the computer or shut it down. Sooner or later either the mini-pager does not appear, or Desk 0 does not change with Desk 1 but leaves a shadow.

What do I mean by shadow symptom?
1. Fresh login
2. Load xterm or other apps in Desk 0.
3.  Click Desk 1 label. The desk is empty but FvwmPager's mini-window shows Desk 0 apps. It supports to be empty. This is what v1.0.9 and other earlier versions do.

Here I am testing with fresh install and default. Running on a laptop. It is supposed to be flawless. Please, get more people to test v1.1.0. I will also find another computer, not have a surprising hardware issue.

**Comment by ThomasAdam** [comment]
@rasatpc 

I cannot reproduce this -- for me, FvwmPager is correctly updating when I change desks.

**Comment by ThomasAdam** [comment]
> Please, get more people to test v1.1.0.

You'll need to do better than this, beyond just saying it.  If you know of people who can, then please mention it to them.  Otherwise, this is a hollow statement.

**Comment by rasatpc** [comment]
Thank you, the latest update of 1.1.0 main branch works now well with all the FvwmPager options that I complained about. Thanks.
